### ISSUE TITLE
Is possible to load a gexf without all that data on nodes and other on edges?

### ISSUE THREAD

**Issue by cryptid11** [edsu/solrpy#40]
I see here https://github.com/jacomyal/sigma.js/blob/master/examples/data/arctic.gexf and there is also the position for every single node!

Isn't there a settings to let it chose by the render? (I have just node id and number, and on the edge side I have also the weight... maybe I simple have to continue browsing graphs)

**Comment by edsu** [comment]
I don't see what this has to do with solrpy.
